---
name: Marie
surname: Curie
position: "Professor"
address: "School of Physics & Chemistry,\\tabularnewline École Normale Supérieure"
phone: +1 22 3333 4444
www: mariecurie.com
email: "Marie.Curie@ens.fr"
twitter: mariecurie
github: mariecurie
linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::hyndman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
here::i_am("CV-Test-Hyndman/CV-Test-Hyndman.Rmd")
library(here)
library(readr)
library(vitae)
library(tibble)

# source(here("R/table.R"))
```

```{r read_cv, include=FALSE}
cv <- read_rds(here("data/cv.Rds"))
```

# Thai Not work yet



# H1

## H2

### H3

#### H4

-   Bullet level 1

    -   Bullet level 2

        -   Bullet level 3

            -   Bullet level 4


# Basic `detailed_entries`

```{r}
tibble(what = rep("What field", 2),
       when = rep("Start - End", 2),
       with = rep("With field", 2),
       where = rep("Where field", 2),
       why = c("Why 1", "Why 2")
       ) %>%    
  detailed_entries(what = what, 
                   when = when, 
                   with = with, 
                   where = where, 
                   why = why)
```

# Basic `brief_entries`

```{r}
tibble(what = rep("What field", 2),
       when = rep("Start - End", 2),
       with = rep("With field", 2),
       where = rep("Where field", 2),
       why = c("Why 1", "Why 2")
       ) %>% 
  brief_entries(what = what, 
                when = when, 
                with = with)
```

# Tricks
## Bold

\textbf{greatest}

```{r latex_bold}
latex_bold <- function(text) {

  glue::glue("\\textbf{<text>}",
             .open = "<", .close = ">")
}

tibble(
  color = latex_bold("Bold Text")
       ) %>%
  detailed_entries(what = color, .protect = F)
```


## Color

```{r latex_color}
latex_color <- function(text, color = "red") {
  
  glue::glue("\\textcolor{<color>}{<text>}",
             .open = "<", .close = ">")
}

latex_color("text")
```


```{r}
tibble(
  color = latex_color("TextColor", color = "red")
       ) %>% 
  detailed_entries(what = color, .protect = F)
```


## Link to Webpage

[link](https://www.google.com)

[\textcolor{blue}{link}](https://www.google.com) 

\href{http://www.latex-tutorial.com}{\textcolor{blue}{link}}


```{r latex_hyperlink}
latex_hyperlink <- function(text, url, color = "blue") {
  
  glue::glue("\\href{<url>}{\\textcolor{<color>}{<text>}}",
             .open = "<", .close = ">")
  
}

latex_hyperlink("Link", "http://www.latex-tutorial.com")
```

```{r}
tibble(
  link = latex_hyperlink("LinkParse", 
                               "http://www.latex-tutorial.com", color = "red")
       ) %>% 
  detailed_entries(what = link, .protect = F)
```


## New line in tibble

```{r new line}
tibble(text = "Some text \\\\ Now, new line") %>% 
  detailed_entries(what = text, .protect = F)
```


## Footer


```{r}
hi <- "hey"
```


\rfoot{`r hi`}


`latex_foot` not working

```{r latex_foot}
latex_foot <- function(text, side = c("right", "left", "center")) {
  
  side <- match.arg(side)
  
  s <- switch (side,
    "right" = { "r" },
    "left" = { "l" },
    "center" = { "c" },
  )
  
  glue::glue("\\<s>foot{<text>}",
    .open = "<", .close = ">"
    )
}


tibble(foot = latex_foot("To Foot")) %>% 
    detailed_entries(with = foot, .protect = F)
```


# Education


```{r}
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Informal studies", "1889-91", "Flying University", "Warsaw, Poland",
  "Master of Physics", "1893", "Sorbonne Université", "Paris, France",
  "Master of Mathematics", "1894", "Sorbonne Université", "Paris, France"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Nobel Prizes

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
  ) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

# Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```
